### ISSUE TITLE
Game Of life problem

### ISSUE THREAD

**Issue by abhishekpopli** [abhishek-nigam/dsa-in-c-cpp#4]
https://leetcode.com/problems/game-of-life/
medium level leetcode question asked in interviews

**Comment by abhishek-nigam** [comment]
Never heard about this problem. It sounds quite interesting, could you please add the problem statement ane solution both.

**Comment by abhishekpopli** [comment]
kindly review PR and close the issue. Thanks, Abhishek!
https://github.com/abhishek-nigam/dsa-in-c-cpp/pull/5
